
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rogue-cloud-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rogue-cloud-server
    spec:
      containers:
      - name: rogue-cloud
        image: mycluster.icp:8500/default/rogue-cloud:latest
        livenessProbe:
          httpGet:
            path: /RogueCloudServer/RogueCloudServerHealth
            port: 29080
          initialDelaySeconds: 240
          periodSeconds: 900

