kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-pv-claim
spec:
  storageClassName: {{ .Values.storageclass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
